language: python
cache: pip
python: 2.7
install:
  - pip install -q -r requirements .
script: true
notifications:
  email: false
deploy:
  provider: pypi
  user: paolo.garri
  password:
    secure: Gfi/u4wXaPSku4P1ZrojQEO2yFM+LSOAD6v6HFejgCbARO3fH2qfkXV5hEJNaRN5n+LOP7YW6Q5MToSSioAr3OwAZ/aP53HVlZCloB+y4Agd2prV2puuicVJUtKdUYEMsBxCL+TF8siiC+epofEahlsLf+ouTqQIfopzIfD3Gq/XxRuGBmOnplP9+JX3XC4UpnIqTMsus22dpBBJk5E+hBysPttvJXIIJlqqB/Vul9U80mhUJ5HCKtVOf3rT8ntMSJEC6NYzQ+iRc9mma8mzBn8RDfpZgj95D5h9JFUn/bNWCT4CbFnocBQfs6N5W1nQ95V4XyZmRZw6AIsaHPpflB/MscYNRD1g3c+RXtskKmNPeueoh8b9JVXBSHJKDI8sdbX3HT8d5ccHdLOHxTgKMH/ig2XqXLIXyAJfTFSNZbRw/MpBfEhFIn/4F+bkeixMs9hTILdYWWn2HHHGD8sbRBNfClrSIIUlsWa+I1k6qgJdzsee1XQ0YKShOfUc2ZM2Ulqm9Mg3+CL/7zELqLOa11iSyEYtVTKkmul2WM/VYVyfo1B1+7GBvg6QGfANePPhnllSQfdR/yB5LAYCP1/nMcRn7Ompg6b4+Kw2mL+R91UvIYtgBzOIhOshSFraGUTd17RUqBn8RlHglOEqeg9Zj5bq6YHFQ5JdPQ4VacrAEkk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sport1online/thumbor-focus-filter
